
name: feeluown

source:
  host: other
  get_version: curl -s https://pypi.org/pypi/feeluown/json | python3 -c \"import sys, json; print(json.load(sys.stdin)['info']['version'])\"
  method: metapackage

