
name: gridea
license: MIT

only_arches:
  - amd64
  - i386
  - arm64
  - armhf

source:
  host: github
  repo: getgridea/gridea
  method: build
  source_url: https://github.com/getgridea/gridea/releases/download/v##VERSION/gridea_##VERSION_amd64.deb
