
name: lx-music-desktop
license: Apache-2.0

source:
  host: github
  repo: lyswhut/lx-music-desktop
  method: build
  source_url: https://github.com/lyswhut/lx-music-desktop/releases/download/v##VERSION/lx-music-desktop.v##VERSION.x64.deb

