
name: code
license: MIT

only_arches:
  - amd64
  - i386
  - arm64
  - armhf

source:
  host: other
  get_version: curl -s 'https://www.archlinux.org/packages/community/x86_64/code/json/' | python3 -c \"import sys, json; print(json.load(sys.stdin)['pkgver'])\"
  method: build
  source_url: https://github.com/microsoft/vscode/archive/##VERSION.tar.gz

