
name: electron-netease-cloud-music
license: MIT

only_arches:
  - amd64
  - i386
  - arm64
  - armhf

source:
  host: github
  repo: Rocket1184/electron-netease-cloud-music
  method: build
  source_url: empty

