
name: wiznote
license: GPL-3.0

only_arches:
  - amd64
  - i386
  - arm64
  - armhf

source:
  host: other
  get_version: curl -s 'https://www.wiz.cn/as/blogs/wiznote-linux.html' | sed 's/.*建议分支： *\([0-9\.]*\).*/\1/g'
  method: build
  source_url: https://github.com/WizTeam/WizQTClient/archive/##VERSION.tar.gz
