
name: draw.io
license: Apache-2.0

source:
  host: github
  repo: jgraph/drawio-desktop
  method: build
  source_url: https://github.com/jgraph/drawio-desktop/releases/download/v##VERSION/draw.io-amd64-##VERSION.deb
